[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
default-run = "day3"

[dependencies]
regex = "1.5.4"
partial_application = "0.2.1"
strum = "0.25"
strum_macros = "0.25"
memoize = "0.4.1"

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"
